# Generated by Django 3.2.3 on 2021-05-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0002_delete_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.songs')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.users')),
            ],
        ),
    ]
